### ISSUE TITLE
Something went wrong when registering

### ISSUE THREAD

**Issue by keinstein** [mb21/iCalendar-to-Facebook-Event#1]
I registered an account for a product (in fact an open source computer application) and tried to add a calendar to it using iCalendar to event. Unfortunately it did not work as I get always the following error message 

Fatal error: Uncaught exception 'FacebookRestClientException' with message 'Session key invalid or no longer valid' in /home/www/web27/html/ics-to-fbevent/facebook/facebookapi_php5_restlib.php:3065 Stack trace: #0 /home/www/web27/html/ics-to-fbevent/facebook/facebookapi_php5_restlib.php(1758): FacebookRestClient->call_method('facebook.users....', Array) #1 /home/www/web27/html/ics-to-fbevent/index.php(54): FacebookRestClient->users_hasAppPermission('offline_access') #2 {main} thrown in /home/www/web27/html/ics-to-fbevent/facebook/facebookapi_php5_restlib.php on line 3065

Looking into the sources it seems that it would be sufficient to catch these events. The error is fatal as I cannot remove or readd the application as it stays inaccessible.

**Comment by mb21** [comment]
This is not a calendar program in the ordinary sense:

This is a Facebook Application you can use to subscribe to an iCalendar file which then gets regularly checked for updates. When new events in the calendar become available, it will create a facebook event in your name.

currently the app is online at 
http://www.facebook.com/apps/application.php?id=164414672850

**Comment by keinstein** [comment]
Please, stay consistent. If you redirect people from Facebook to Github, you must not blame them for posting their bugs there. 

The above error message was seen on Facebook and the only Answer I got said: “Go to github”. Unfortunately there is no information, how to deal with bugs in this application!

If something goes wrong with the registration of this App it should try to recover from that instead of crashing. You are already checking permissions. That is still useless if your script doesn't understand the answer that function returns. It is not so hard to add a try/catch block around line 54 in index.php. If I were a facebook developer I'd deliver a patch for it, but at the moment I'm not interested in facebook development and have not the time to get used to this kind of application.

But an untested patch usually produces more issues than doing nothing. So I decided to finish by providing an analysis of the bug, which obviously was just a waste of time!

Pleas, reopen this issue until it is really fixed.

**Comment by mb21** [comment]
well, it's 'fixed'.
